### ISSUE TITLE
Percona-Server-shared-56装不上去？麻烦看一下，谢谢~~~

### ISSUE THREAD

**Issue by raxxar1024** [Meituan-Dianping/SQLAdvisor#12]
安装的时候报错如图：
![image](https://cloud.githubusercontent.com/assets/16130282/23882922/a8173b16-089e-11e7-9d1c-b4c1797b3adc.png)

配置percona56 yum源已经操作过了。（ yum install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm）

我的系统是阿里云上的centos7。

**Comment by dbarobin** [comment]
我用 yum 安装也不行，于是采用 rpm 包手动安装。

1. 下载 tar 包 

> wget https://www.percona.com/downloads/Percona-Server-5.6/Percona-Server-5.6.25-73.1/binary/redhat/6/x86_64/Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar

2. 解压

> tar -zxvf Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar

3. 找到对应包，安装即可。

> rpm -ivh Percona-Server-shared-56-5.6.25-rel73.1.el6.x86_64.rpm

**Comment by raxxar1024** [comment]
好的，谢谢。我试一下~~~

**Comment by zerkzzzz** [comment]
yum install Percona-Server-client-56 Percona-Server-server-56
这个命令即可

**Comment by yinshengji** [comment]
先安装那个包，然后直接yum install 那个名字就行

**Comment by yuqiangit** [comment]
我用 yum 安装也不行，于是采用 rpm 包手动安装。

下载 tar 包
wget https://www.percona.com/downloads/Percona-Server-5.6/Percona-Server-5.6.25-73.1/binary/redhat/6/x86_64/Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar
解压
tar -zxvf Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar
找到对应包，安装即可。
rpm -ivh Percona-Server-shared-56-5.6.25-rel73.1.el6.x86_64.rpm


我使用这个方案：
解压的时候报错了：
tar -zxvf Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


然后换成：tar -xvf Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar（去掉z参数）

之后执行安装：
warning: Percona-Server-shared-56-5.6.25-rel73.1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID cd2efd2a: NOKEY

请问这个过程有问题吗？

**Comment by goodosoft** [comment]
你这是拿issue 当论坛玩呢，关闭吧

**Comment by mj8star** [comment]
> 我用 yum 安装也不行，于是采用 rpm 包手动安装。
> 
> 下载 tar 包
> wget https://www.percona.com/downloads/Percona-Server-5.6/Percona-Server-5.6.25-73.1/binary/redhat/6/x86_64/Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar
> 解压
> tar -zxvf Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar
> 找到对应包，安装即可。
> rpm -ivh Percona-Server-shared-56-5.6.25-rel73.1.el6.x86_64.rpm
> 
> 我使用这个方案：
> 解压的时候报错了：
> tar -zxvf Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> 
> 然后换成：tar -xvf Percona-Server-5.6.25-73.1-r07b797f-el6-x86_64-bundle.tar（去掉z参数）
> 
> 之后执行安装：
> warning: Percona-Server-shared-56-5.6.25-rel73.1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID cd2efd2a: NOKEY
> 
> 请问这个过程有问题吗？
------------------------------------------
使用 tar -xvf 即可
