### ISSUE TITLE
完成安装测试时提示信息无法解决

### ISSUE THREAD

**Issue by Daikunwu** [Meituan-Dianping/SQLAdvisor#14]
![image](https://cloud.githubusercontent.com/assets/23518469/23991874/d557ee30-0a75-11e7-8823-b35bc539001b.png)
![linux](https://cloud.githubusercontent.com/assets/23518469/23991961/24a69932-0a76-11e7-87e8-eccf25f49523.png)

提示无法处理 -P 所用的整数值“xx”

**Comment by dbarobin** [comment]
xx 只是示例，此处应该填写 MySQL 端口，比如 3306

**Comment by Daikunwu** [comment]
懂了，上面参数有定义，没细看，谢谢
