### ISSUE TITLE
建议代码中添加.gitignore文件，以免使用IDE工具查看项目时自动编译生成的临时文件影响git status

### ISSUE THREAD

**Issue by martianzhang** [Meituan-Dianping/SQLAdvisor#16]
.gitignore文件可以参考mysql-server, mariadb-server提供的ignore文件

**Comment by martianzhang** [comment]
通过使用out-of-source的build方法可以临时解决这个问题 :)
参考http://blog.plecharts.cz/2013/04/true-out-of-source-builds-in-netbeans.html

**Comment by liangry** [comment]
https://github.com/liangry/SQLAdvisor
latest commit fixed
