### ISSUE TITLE
安装SQLAdvisor源码时出错

### ISSUE THREAD

**Issue by ladder1984** [Meituan-Dianping/SQLAdvisor#17]
按照https://github.com/Meituan-Dianping/SQLAdvisor/blob/master/doc/QUICK_START.md ，执行到1.4中的第三步make时报错，内容如下：
```
Linking CXX executable sqladvisor
/usr/bin/ld: cannot find -lperconaserverclient_r
collect2: 错误：ld 返回 1
make[2]: *** [sqladvisor] 错误 1
make[1]: *** [CMakeFiles/sqladvisor.dir/all] 错误 2
make: *** [all] 错误 2
```

系统信息：
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.0.1406 (Core)
Release:	7.0.1406
Codename:	Core
```

**Comment by tsthght** [comment]
有没有按文档做 软链？ln -s libperconaserverclient_r.so.18 libperconaserverclient_r.so

**Comment by ladder1984** [comment]
的确是忘了软链。。。
yum install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm之后yum install --enablerepo=Percona56 Percona-Server-shared-56时候提示找不到repository，最后yum install Percona-Server-shared-56。。这么之后直接有那个文件，不用软链，也能正常使用。。。不知道会不会有什么问题
