### ISSUE TITLE
此项目目前还维护吗？

### ISSUE THREAD

**Issue by pangPython** [Meituan-Dianping/SQLAdvisor#78]
此项目目前还维护吗？

**Comment by myide** [comment]
可以关注项目https://github.com/myide/see，基于Django+Vue 支持SQLAdvisor WEB界面，若此处有维护会及时更新

**Comment by myide** [comment]
可以关注项目https://github.com/myide/see，支持SQLAdvisor WEB界面，若此处有维护会及时更新

**Comment by myide** [comment]
可以关注mysql web项目，支持SQLAdvisor WEB界面，若此处有维护会及时更新，git地址： https://github.com/myide/see，

**Comment by myide** [comment]
可以关注mysql web项目，支持SQLAdvisor WEB界面，若此处有维护会及时更新，git地址： https://github.com/myide/see
