### ISSUE TITLE
/usr/bin/ld: cannot find -lperconaserverclient_r

### ISSUE THREAD

**Issue by dbarobin** [Meituan-Dianping/SQLAdvisor#9]
安装 SQLAdvisor 源码这一步，当执行 make 时提示如下错误信息：

> Linking CXX executable sqladvisor
> /usr/bin/ld: cannot find -lperconaserverclient_r
> collect2: ld returned 1 exit status
> make[2]: *** [sqladvisor] Error 1
> make[1]: *** [CMakeFiles/sqladvisor.dir/all] Error 2
> make: *** [all] Error 2

版本信息如下：

* cmake: cmake version 2.8.12.2
* glibc: glibc-2.12-1.166.el6_7.7.x86_64

注：已通过 rpm 包安装  **Percona-Server-shared-56-5.6.25-rel73.1.el6.x86_64.rpm**

谢谢。

**Comment by tsthght** [comment]
按照文档做 软链 了么？

编译sqladvisor时依赖perconaserverclient_r, 因此需要安装Percona-Server-shared-56。有可能需要配置软链接例如:1. cd /usr/lib64/ 2. ln -s libperconaserverclient_r.so.18 libperconaserverclient_r.so

**Comment by dbarobin** [comment]
@tsthght  抱歉哈，这一步丢了，非常感谢。
